[package]
name = "swift_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5.4"
chrono = "0.4.19"
iso-4217 = "0.1.0"
iso3166-1 = "1.0.1"